### ISSUE TITLE
getMarketInfo returning an object instead of an array

### ISSUE THREAD

**Issue by quarkmarino** [Achse/php-shapeshift-io-api#2]
Hi, I'm receiving this error on calling the getMarketInfo() method, 

Type error: Return value of Achse\ShapeShiftIo\Client::getMarketInfo() must be of the type array, object returned 

I somehow fixed by changing the expected return type from array to stdClass but not sure if it is totally correct

**Comment by Achse** [comment]
Hi @quarkmarino, thanks a lot for the report.

It's indeed a bug. I've fixed it by splitting method into  `getMarketInfo(..): stdClass` (with required parameters) and `getWholeMarketInfo(): array` with no parameters. Tagged updated beta release: https://github.com/Achse/php-shapeshift-io-api/releases/tag/0.0.2
