### ISSUE TITLE
Does it cover all APIs offered by Shapeshift?

### ISSUE THREAD

**Issue by kadnan** [Achse/php-shapeshift-io-api#3]
Not an issue but I want to know whether I can use it for things like converstion , sending/receiving tokens?

**Comment by Achse** [comment]
Hi, all supported endpoints are mentioned here: https://github.com/Achse/php-shapeshift-io-api/blob/master/src/Resources.php

If you miss endpoint or you want to implement any changes I'll be happy for every pull request.
